[project]
name = "langchain-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Trishna Paswan", email = "S24CSEU0083@bennett.edu.in" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "langchain>=1.3.17",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.3.5",
    "langchain-groq>=1.1.3",
    "langchain-openai>=1.6.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
langchain-learning = "langchain_learning:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
